[package]
name = "rust-pruner"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
world-test = []

[[bin]]
name = "prune-world-test"
path = "src/bin/prune_world_test.rs"
required-features = ["world-test"]

[dependencies]
mca = "2.1.2"
simdnbt = "0.10.0"
flate2 = "1"
rayon = "1"
walkdir = "2"
jni = "0.21"
rawzip = "0.4.4"
